version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_net
    depends_on:
      - wordpress

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_net
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception_net

networks:
  inception_net:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/opernod/data/mariadb

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/opernod/data/wordpress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
