[www]
user = www-data
group = www-data

; On fait écouter PHP-FPM sur le port 9000 pour communiquer avec NGINX
listen = 9000
listen.owner = www-data
listen.group = www-data

pm = dynamic
pm.max_children = 25
pm.start_servers = 5
pm.min_spare_servers = 1
pm.max_spare_servers = 10
